//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parcel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Parcel()
        {
            this.Invoices = new HashSet<Invoice>();
            this.Routes = new HashSet<Route>();
            this.ShipFees = new HashSet<ShipFee>();
        }
    
        public int parcelID { get; set; }
        public string parcelName { get; set; }
        public double parcelMass { get; set; }
        public string parcelSize { get; set; }
        public Nullable<double> parcelValue { get; set; }
        public System.DateTime createTime { get; set; }
        public string RCustomerID { get; set; }
        public string SCustomerID { get; set; }
        public Nullable<bool> type { get; set; }
        public bool shippingMethod { get; set; }
        public Nullable<bool> parcelStatus { get; set; }
        public Nullable<bool> isCOD { get; set; }
        public string currentWarehouseID { get; set; }
        public Nullable<bool> isFinalWarehouse { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Customer Customer1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Route> Routes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShipFee> ShipFees { get; set; }
    }
}
