//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipFee
    {
        public int shippingFeeID { get; set; }
        public bool shippingMethod { get; set; }
        public double totalCost { get; set; }
        public double locations { get; set; }
        public int parcelID { get; set; }
    
        public virtual Parcel Parcel { get; set; }
    }
}
